### ISSUE TITLE
Let linguex manage judgement symbols

### ISSUE THREAD

**Issue by haoming-li-ling** [amunn/expex-glossonly#1]
At the moment, 
```latex
\ex. * 
\begingl
\gla ... //
\glb ... //
\glft ... //
\endgl
```
results in large unwanted horizontal space between the judgement symbol and the gloss structure; I have to use the much more verbose expex way of handling judgement symbols:
```latex
\ex. 
\begingl
\gla \nogloss{\ljudge{*}} @  ... //
\glb ... //
\glft ... //
\endgl
```
Is there a way for the first way of introducing judgement symbols work as intended?

**Comment by amunn** [comment]
Thanks for the report. I'm not sure where the extra space is coming from. But you don't need to wrap `\ljudge` in `\nogloss`, so can just do `\ljudge{*}` inside the gloss. Since this isn't that much more complicated than using the `linguex` method, I'm not going to prioritize fixing this, although I'll leave the issue open.

**Comment by amunn** [comment]
Here's a temporary fix. I may incorporate this into the package. Please let me know if this causes other problems, as I don't use `linguex` at all. 

```
\makeatletter
\renewcommand\EPGL@setglossmargin{\setlength{\leftskip}{0pt}}
\makeatother

**Comment by amunn** [comment]
The temporary fix isn't the actual fix. The new version has been uploaded to CTAN and should appear in a couple of days.

**Comment by haoming-li-ling** [comment]
Thanks for your update! With my documents I have to use `\nogloss{}`, I don't know why. Also the updated version does fix the problem for first-level examples and the first example in a multi-part example; however, the subsequent examples in a multi-part example display a different kind of weird spacing issue, if they don't have a judgement symbol:
```latex
\ex. 
\a. *
\begingl
\gla Zhangsan qi na-pi ma  meiyou qi. //
\glb Z. ride that-\textsc{cl} horse  \textsc{neg} ride-\textsc{pfv}  //
\glft `Zhangsan did not ride the horse.' //
\endgl
\b. \begingl
\gla Zhangsan qi na-pi ma  MEIYOU qi. //
\glb Z. ride that-\textsc{cl} horse  \textsc{neg} ride-\textsc{pfv}  //
\glft `Zhangsan indeed did not ride the horse.' //
\endgl
```
gives the following:
<img width="383" alt="image" src="https://github.com/amunn/expex-glossonly/assets/57542275/37c5522c-92ba-420f-9b2c-8ad9a7e8962a">

**Comment by amunn** [comment]
@haoming-li-ling Thanks for the report. Can you try the new version I've just pushed? I think that solves the problem.

**Comment by haoming-li-ling** [comment]
Sorry for the late reply. This works. Can you push it to ctan?

**Comment by amunn** [comment]
@haoming-li-ling  Thanks for responding. I've pushed a new version to CTAN. It should appear in the next couple of days.
